AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'lib/payrix/http/request_params.rb'
    - 'lib/payrix/resource/**/*.rb'
    - 'lib/payrix/resource.rb'
    - 'spec/lib/payrix/**/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
