require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'lib/payrix/http/request_params.rb'
    - 'lib/payrix/resource/**/*.rb'
    - 'lib/payrix/resource.rb'
    - 'spec/lib/payrix/resource/**/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

RSpec/NestedGroups:
  Max: 4
