inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    # These files will eventually be removed from the library, so don't bother fixing them up.
    - 'lib/payrix/http/request_params.rb'
    - 'lib/payrix/resource/**/*.rb'
    - 'lib/payrix/resource.rb'
    - 'spec/lib/payrix/resource/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/MethodLength:
  # The default of 10 felt too restrictive.
  Max: 15

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Exclude:
    # Documentation and descriptions for API resources should be found in the official Payrix API documentation.
    - 'lib/payrix/resources/**/*.rb'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets
