require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'lib/payrix/http/request_params.rb'
    - 'lib/payrix/resource/**/*.rb'
    - 'lib/payrix/resource.rb'
    - 'spec/lib/payrix/resource/**/*.rb'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  EnforcedStyle: brackets
