# frozen_string_literal: true

module Payrix
  class Payment
    METHOD_AMERICAN_EXPRESS = 1
    METHOD_VISA = 2
    METHOD_MASTERCARD = 3
    METHOD_DINERS_CLUB = 4
    METHOD_DISCOVER = 5
    METHOD_CHECKING_ACCOUNT = 8
    METHOD_SAVINGS_ACCOUNT = 9
    METHOD_CORPORATE_CHECKING_ACCOUNT = 10
    METHOD_CORPORATE_SAVINGS_ACCOUNT = 11
  end
end
