# frozen_string_literal: true

module Payrix
  class Txn < BaseResource
    RESOURCE_ENDPOINT = 'txns'

    STATUS_PENDING = 0
    STATUS_APPROVED = 1
    STATUS_FAILED = 2
    STATUS_CAPTURED = 3
    STATUS_SETTLED = 4
    STATUS_RETURNED = 5

    ORIGIN_CREDIT_CARD_TERMINAL = 1
    ORIGIN_ECOMMERCE_SYSTEM = 2
    ORIGIN_MAIL_ORDER = 3
    ORIGIN_APPLE_PAY = 4
    ORIGIN_3D_SECURE_SUCCESSFUL = 5
    ORIGIN_3D_SECURE_ATTEMPTED = 6
    ORIGIN_RECURRING_CARD_TRANSACTION = 7
    ORIGIN_PAYFRAME = 8

    TYPE_SALE_TRANSACTION = 1
    TYPE_AUTH_TRANSACTION = 2
    TYPE_CAPTURE_TRANSACTION = 3
    TYPE_REVERSE_AUTHORIZATION = 4
    TYPE_REFUND_TRANSACTION = 5
    TYPE_ECHECK_SALE_TRANSACTION = 7
    TYPE_ECHECK_REFUND_TRANSACTION = 8
    TYPE_ECHECK_REDEPOSIT_TRANSACTION = 11
    TYPE_ECHECK_ACCOUNT_VERIFICATION_TRANSACTION = 12

    COF_TYPE_SINGLE = 'single'
    COF_TYPE_SCHEDULED = 'scheduled'
    COF_TYPE_UNSCHEDULED = 'unscheduled'

    extend Payrix::APIOperations::DeleteDisabled
  end
end
